---
name: 'Test'

on:
  push:

jobs:
  integration:
    needs: 'lint-unit'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - centos-7
        suite:
          - default
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: Dokken
        uses: actionshub/test-kitchen@main
        env:
          CHEF_LICENSE: accept-no-persist
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}

  final:
    runs-on: ubuntu-latest
    needs: [integration]
    steps:
      - run: echo ${{needs.integration.outputs}}